name: GPU Builds and Tests

on:
  create:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - llama3

jobs:
  build-and-test-llama3:
    runs-on: ubicloud-gpu-standard-1-latest
    env:
      HF_TOKEN: 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
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "::add-mask::$HF_TOKEN"

      - name: Install OpenMP
        run: sudo apt-get update && sudo apt-get install -y libomp-dev

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python dev/data/tinyshakespeare.py --model_desc llama-3

      - name: Train model
        run: python train_llama3.py --write_tensors 1 --dtype float32 --offload 1

      - name: Build FP32 precision
        run: PRECISION=FP32 make test_llama3cu

      - name: Run default
        run: ./test_llama3cu

      - name: Build BF16 precision
        run: PRECISION=BF16 make train_llama3cu test_llama3cu

      - name: Run default
        run: ./test_llama3cu
